blank_issues_enabled: true
contact_links:
  - name: (PLDW) Data Analysis/Visualizations, Alerts, Access, and/or Management Request
    url: https://github.com/protocol/pldw/issues/new/choose
    about: Requests for accessing PLDW data, managing Grafana dashboards, application logs, and other data artifacts should be directed here.
