blank_issues_enabled: true
contact_links:
  - name: (PLDW) Data Alerts, Access, Management or Analysis
    url: https://github.com/protocol/pldw/issues/new/choose
    about: Requests for accessing Sentinel data, managing Grafana dashboards, application logs, and other data artifacts
